apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: nodejs
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: nodejs
    tier: frontend
